### ISSUE TITLE
Need To Be Responsive

### ISSUE THREAD

**Issue by B1TSH3LL** [B1TSH3LL/Virtual_Keyboard#1]
I Need Someone to Assist Me Because I'm a Little Busy. Simply make this project device responsive.

**Comment by B1TSH3LL** [comment]
You Changed Whole Code I Dont Need That Just Go Through My Code And Appearance Just Go With It

**Comment by B1TSH3LL** [comment]
You Changed the whole ui

**Comment by S0han** [comment]
ill take a look anything specific you want done with this?

**Comment by B1TSH3LL** [comment]
No just make it responsive both text area and glow should be responsive keep the design same don't change it

**Comment by S0han** [comment]
done.
